server:
  port: 8080
spring:
  application:
    name: AAS-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    .pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eas_by_crpc?useSSL=false&tinyInt1isBit=false
    username: root
    password: 233233
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: HiHikariPool
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    mongodb:
      uri: mongodb://admin:admin@192.168.248.128:27017/EAS_By_CRPC?authSource=admin&authMechanism=SCRAM-SHA-1
  redis:
    host: 192.168.248.128
    port: 6379
    database: 0
    timeout: 5000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true